### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kasci** [laserbat/RogueNano#1]
Hello, when I try to run it it returns syntax error ...

**Comment by Kasci** [comment]
No I have this error  .... Can't locate Curses.pm in @INC (you may need to install the Curses module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at ./game line 2.

**Comment by laserbat** [comment]
You have to install libcurses-perl package for it to work. Might be named differently in your linux distro.
